site_name: Documentation de my_module
theme:
  name: material
  custom_dir: theme
  favicon: assets/favicon.ico

nav:
  - Home: index.md
  - my_module: my_module.md
  - Tests: tests.md

# Extensions supplémentaires (facultatives)
plugins:
  - search

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

# Configuration de la couverture
extra:
  coverage_report: "coverage/index.html"

# Options pour l'URL (optionnel)
site_url: https://ali-d-debug/Le-projet/
